### ISSUE TITLE
Support Streaming API

### ISSUE THREAD

**Issue by sys1yagi** [sys1yagi/mastodon4j#19]
https://github.com/tootsuite/documentation/blob/master/Using-the-API/Streaming-API.md
https://github.com/tootsuite/mastodon/blob/master/streaming/index.js#L275

**Comment by MulticolorWorld** [comment]
One of ideas I write
https://github.com/MulticolorWorld/mastodon4j/commit/c51987f84898878e8c1689ad99c625a9db252740

**Comment by sys1yagi** [comment]
🆒

**Comment by MulticolorWorld** [comment]
Where is writing about streaming/public/local on api documentation? I don't found.

**Comment by sys1yagi** [comment]
I found it in the source code.
https://github.com/tootsuite/mastodon/blob/master/streaming/index.js#L303

**Comment by MulticolorWorld** [comment]
Thank you!
