### ISSUE TITLE
 Is this project alive?

### ISSUE THREAD

**Issue by Sciss** [sys1yagi/mastodon4j#88]
Seems last commits are three, four years old. https://docs.joinmastodon.org/client/libraries/ still lists it as the only Java project. Is there an alternative up-to-date Java project? Thanks

**Comment by takeshitakenji** [comment]
Maybe we should create one.

**Comment by Sciss** [comment]
I'm keeping a low-level maintenance of [Scaladon](https://github.com/Sciss/scaladon) now.
